# Generated by Django 5.0 on 2023-12-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='regular_price',
        ),
    ]
